Data Exchange: Course Offerings XML Import
- removed hibSession.refresh(clazz) that was causing a NullPointerException in Hibernate 6.6

  NullPointerException: Cannot invoke "org.hibernate.engine.spi.EntityEntry.getMaybeLazySet()" because "entityEntry" is null