Dependencies Update
- fixed sending emails from the solver server; angus-activation dependency was missing causing the following error:
  jakarta.activation.UnsupportedDataTypeException: no object DCH for MIME type multipart/mixed
- caused by the update in commit 51762e6