CPSolver Fix
- new build of the CPSolver (same version, as of September 25)
- this fixes the NoSuchMethodError: GroupConstraint.getType()
  (caused by using a continous build)