Login / Login Required screen  - if there was an error during application startup, print an error message at the bottom of the page. This message include a short snippet of the exception, for example:
	UniTime 3.2.10 failed to start up properly, please check the application log for more details.

	HibernateException: Could not create a DBCP pool (at DBCPConnectionProvider.java:178)
	SQLNestedException: Cannot create PoolableConnectionFactory (ORA-01017: invalid username/password; logon denied ) (at BasicDataSource.java:1549)
	SQLException: ORA-01017: invalid username/password; logon denied (at T4CTTIoer.java:439)

This should help the users that are trying to install / use the application to identify why they are not able to login into the application.