Multiple Class Setup: Bugfix
- only remove the class from its subpart after the related objects (like exams) have been deleted
  - this fixes the
    StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1
  - when two classes are being deleted, each with an exam attached to it
    (the exam lookup in the delete of related objects of the second class was causing both classes to be deleted before the remove was called on the second one as the class was already removed from the subpart when the exam lookup was called)